basePath: /
definitions:
  structs.Login:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  structs.NoteCreate:
    properties:
      subtitle:
        type: string
      text:
        type: string
      title:
        type: string
    required:
    - subtitle
    - text
    - title
    type: object
  structs.RoleCreate:
    properties:
      display:
        type: string
      name:
        type: string
    required:
    - display
    - name
    type: object
host: 127.0.0.1:3000
info:
  contact:
    email: wigunaahmadaulia@gmail.com
    name: Aulia Wiguna
    url: https://github.com/auliawiguna/
  description: This is an API boilerplate using Golang
  title: Goshaka Golang API Starter
  version: "1.0"
paths:
  /api/v1:
    get:
      consumes:
      - application/json
      description: Show greeting
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Say hi
      tags:
      - Root
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: email
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/structs.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Login
      tags:
      - Auth
  /api/v1/auth/my-profile:
    get:
      consumes:
      - application/json
      description: My Profile
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: My Profile
      tags:
      - Auth
  /api/v1/notes:
    get:
      consumes:
      - application/json
      description: Show notes
      parameters:
      - default: 10
        description: Default 10
        in: query
        name: limit
        type: integer
      - default: 1
        description: Default 10
        in: query
        name: page
        type: integer
      - description: Sorting
        enum:
        - ID asc
        - ID desc
        - title asc
        - title desc
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show notes
      tags:
      - Notes
    post:
      consumes:
      - application/json
      description: Create new note
      parameters:
      - description: title
        in: body
        name: notesRequest
        required: true
        schema:
          $ref: '#/definitions/structs.NoteCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Create new note
      tags:
      - Notes
  /api/v1/notes/{id}:
    delete:
      consumes:
      - application/json
      description: Delete existing note
      parameters:
      - default: 10
        description: ID
        in: path
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Delete existing note
      tags:
      - Notes
    get:
      consumes:
      - application/json
      description: Show detail note
      parameters:
      - default: 10
        description: ID
        in: path
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show detail note
      tags:
      - Notes
    put:
      consumes:
      - application/json
      description: Update existing note
      parameters:
      - default: 10
        description: ID
        in: path
        name: id
        type: integer
      - description: title
        in: body
        name: notesRequest
        required: true
        schema:
          $ref: '#/definitions/structs.NoteCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Update existing note
      tags:
      - Notes
  /api/v1/protected:
    get:
      consumes:
      - application/json
      description: Show greeting
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Say hi
      tags:
      - Root
  /api/v1/roles:
    get:
      consumes:
      - application/json
      description: Show roles
      parameters:
      - default: 10
        description: Default 10
        in: query
        name: limit
        type: integer
      - default: 1
        description: Default 10
        in: query
        name: page
        type: integer
      - description: Sorting
        enum:
        - ID asc
        - ID desc
        - title asc
        - title desc
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Show roles
      tags:
      - Roles
    post:
      consumes:
      - application/json
      description: Create new role
      parameters:
      - description: title
        in: body
        name: rolesRequest
        required: true
        schema:
          $ref: '#/definitions/structs.RoleCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Create new role
      tags:
      - Roles
  /api/v1/roles/{id}:
    delete:
      consumes:
      - application/json
      description: Delete existing role
      parameters:
      - default: 10
        description: ID
        in: path
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Delete existing role
      tags:
      - Roles
    get:
      consumes:
      - application/json
      description: Show detail role
      parameters:
      - default: 10
        description: ID
        in: path
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Show detail role
      tags:
      - Roles
    put:
      consumes:
      - application/json
      description: Update existing role
      parameters:
      - default: 10
        description: ID
        in: path
        name: id
        type: integer
      - description: title
        in: body
        name: rolesRequest
        required: true
        schema:
          $ref: '#/definitions/structs.RoleCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Update existing role
      tags:
      - Roles
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
